### ISSUE TITLE
Some bugs of the new update

### ISSUE THREAD

**Issue by conscnt1** [zThana/RacesOfThana#3]
- When you change races, the attributes that the previous look had are transferred to the other race if that race does not have that attribute value
- Initial races when deleted from the files reappear on reloading

**Comment by conscnt1** [comment]
- When changing a race, if the original one had idle sounds, but the final one didn't, this sound is also transferred to the new race, and also spams with the error "Invalid sound key: customnamespace:CUSTOM.SOUND"

**Comment by zThana** [comment]
Hi, thank you for reporting these bugs. Next time, please separate the bugs to make it easier to track 😊
These bugs will be fixed in v4.0.3. Thank you for contributing 🙏
